import fs from 'node:fs';

const dataPath = 'src/data.ts';
const existing = fs.readFileSync(dataPath, 'utf8');
const parse = (re, name) => {
  const match = existing.match(re);
  if (!match) throw new Error(`Missing last-known-good ${name}`);
  return JSON.parse(match[1]);
};

let market = parse(/export const MARKET = (\{.*?\});/s, 'market');
let prices = parse(/export const PRICES: \[number, number\]\[\] = (\[.*?\]);\n\nexport interface/s, 'prices');
let txs = parse(/export const TXS: Tx\[\] = (\[.*\]);/s, 'transactions');

async function json(url) {
  const response = await fetch(url, { headers: { accept: 'application/json', 'user-agent': 'Vilcyan/btc-portfolio GitHub Actions' } });
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  return response.json();
}

try {
  const simple = await json('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_24hr_change=true&include_last_updated_at=true');
  const currentPrice = Number(simple?.bitcoin?.usd);
  if (!Number.isFinite(currentPrice) || currentPrice <= 0) throw new Error('Invalid CoinGecko current price');
  const change24h = Number(simple?.bitcoin?.usd_24h_change);
  market = {
    currentPrice,
    change24h: Number.isFinite(change24h) ? change24h : market.change24h,
    updatedAt: new Date((simple.bitcoin.last_updated_at || Date.now() / 1000) * 1000).toISOString(),
    source: 'CoinGecko'
  };
  console.log(`Price refreshed: ${currentPrice}`);
} catch (error) {
  if (!market.currentPrice) throw error;
  console.warn(`Price refresh failed, keeping last-known-good: ${error.message}`);
}

try {
  const now = Math.floor(Date.now() / 1000);
  const from = prices[0]?.[0] || Math.floor(new Date('2022-01-01T00:00:00Z').getTime() / 1000);
  const chart = await json(`https://api.coingecko.com/api/v3/coins/bitcoin/market_chart/range?vs_currency=usd&from=${from}&to=${now}`);
  const byDay = new Map(prices.map(([ts, price]) => [Math.floor(ts / 86400) * 86400, price]));
  for (const [ms, price] of chart.prices || []) {
    const day = Math.floor(ms / 1000 / 86400) * 86400;
    if (Number.isFinite(Number(price)) && Number(price) > 0) byDay.set(day, Number(price));
  }
  const next = [...byDay.entries()].sort((a, b) => a[0] - b[0]);
  if (next.length < prices.length) throw new Error('Incomplete CoinGecko price history');
  prices = next;
  console.log(`History refreshed: ${prices.length} daily points`);
} catch (error) {
  console.warn(`History refresh failed, keeping last-known-good: ${error.message}`);
}

if (process.env.REFRESH_TRANSACTIONS === 'true') {
  try {
    if (!process.env.TX_FEED_URL) throw new Error('TX_FEED_URL secret is not configured');
    const payload = await json(process.env.TX_FEED_URL);
    const next = payload.transactions;
    if (!Array.isArray(next) || !next.length) throw new Error('Transaction feed is empty');
    txs = next.map((t) => {
      const date = String(t.date);
      const ts = Math.floor(new Date(`${date}T00:00:00Z`).getTime() / 1000);
      const btc = Number(t.btc), price = Number(t.price);
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(btc) || !Number.isFinite(price) || !['Mua', 'Bán'].includes(t.type)) throw new Error('Invalid transaction row');
      return { date, ts, type: t.type, btc, price, usd: Number(t.usd) || Math.abs(btc * price), vnd: Number(t.vnd) || 0 };
    });
    console.log(`Transactions refreshed: ${txs.length}`);
  } catch (error) {
    console.warn(`Transaction refresh failed, keeping last-known-good: ${error.message}`);
  }
}

fs.writeFileSync(dataPath,
  `// Generated by scripts/fetch-data.mjs. Public site data only; no Google credentials.\n` +
  `export const MARKET = ${JSON.stringify(market)};\n` +
  `export const PRICES: [number, number][] = ${JSON.stringify(prices)};\n\n` +
  `export interface Tx { date: string; ts: number; type: string; btc: number; price: number; usd: number; vnd: number }\n` +
  `export const TXS: Tx[] = ${JSON.stringify(txs)};\n`
);
